# 🗒️ Syllabus

The lecture slides, notes, tutorials, and assignments will be posted on <ins> [this drive](https://drive.google.com/drive/folders/1B0uJ7dxJpP6gP1hFokGpI8PdGc6cYrM4?usp=share_link) </ins>, feel free to jump on it. please do not anticipate questions that we will address in class, instead [drop me a mail](mailto:niccolo.salvini27@gmail.com) if you are not sure about something.

If for any reasons you have trouble accessing the G Drive, still please contact [your teaching assistant](mailto:niccolo.salvini27@gmail.com). One common issue students complain is that you may need to be authorization to access, because I may have forgotten to switch on the open to share option. If you see me, knock me on the shoulder!

This schedule is subject to change according to the pace of the class and we may schedule a further lab if you feel you are not really ready for the intermediate exam.

This is the updated edition of this course with Dr. Niccolò Salvini (Part 1) and Prof. Sophie Dabo-Niang (Part 2).

## Course Materials

All course materials are available in the `slides/` folder:

### Part 1: The Foundations (Dr. Niccolò Salvini)
- [Hypothesis Testing with Null Hypothesis](slides/02_hypt_testing_null_hypo.pdf)
- [Hypothesis Testing with Alternative Hypothesis](slides/03_hypt_testing_alternative_hypo.pdf)
- [How to Calculate P-values](slides/04_how_to_calculate_pvalues.pdf)
- [Hypothesis Testing on Averages](slides/hypt_testing_on_avg.pdf)
- [Exercises on Hypothesis Testing](slides/05_hypt_testing_exeR.pdf)
- [Linear Regression](slides/linear_regression.pdf)
- [Multiple Linear Regression](slides/mlt_lin_reg.pdf)
- [Nonlinear Regression](slides/nonlinear_regression.pdf)

### Part 2: Advanced Modeling (Prof. Sophie Dabo-Niang)
- Materials will be provided during the intensive session (week of November 17th)

## Course Structure

**Part 1: The Foundations (Dr. Niccolò Salvini)**
- 5 hours of integrated labs during regular lectures
- Mondays: 14:00 - 17:00 CET
- Tuesdays: 10:00 - 13:00 CET

**Part 2: Advanced Modeling (Prof. Sophie Dabo-Niang)**
- 5 hours intensive session during the week of November 17th

to be ready: 

| Date        | Description                                                  | Materials                                                                    | Events           |
| ----------- | ------------------------------------------------------------ | ---------------------------------------------------------------------------- | ---------------- |
| [TBD] | Introduction to RStudio + Hypothesis Testing Fundamentals | [Null Hypothesis Testing](slides/02_hypt_testing_null_hypo.pdf) | Laboratory          |
| [TBD] | Alternative Hypothesis Testing + P-values Calculation | [Alternative Hypothesis](slides/03_hypt_testing_alternative_hypo.pdf) | Laboratory |
| [TBD] | How to Calculate P-values | [P-values Calculation](slides/04_how_to_calculate_pvalues.pdf) | Laboratory |
| [TBD] | Hypothesis Testing on Averages | [Testing on Averages](slides/hypt_testing_on_avg.pdf) and [Exercises](slides/05_hypt_testing_exeR.pdf) | Laboratory |
| [TBD] | Chi-Square Tests (more than 2 proportions) | [Null Hypothesis Testing](slides/hypt_testing_null_hypo.pdf) | Laboratory |
| [TBD] | Simple Linear Regression | [Linear Regression](slides/linear_regression.pdf) | Laboratory |
| [TBD] | Multiple Linear Regression | [Multiple Linear Regression](slides/mlt_lin_reg.pdf) | Laboratory |
| [TBD] | Nonlinear Regression + Dummy Variables | [Nonlinear Regression](slides/nonlinear_regression.pdf) | Laboratory |
| [TBD] | First Intermediate Exam (Part 1) | | Exam |
| Week of Nov 17th | Intensive Session - Advanced Modeling | Materials provided during session | Laboratory |
| [TBD] | Second Intermediate Exam (Part 2) | | Exam |



