# ⚡ Course Performance

In this place you can have a grasp on how your previous colleagues performed on past years in this course. Hopefully this will inspire you to do better and challenge your grade expectation.
Data is extracted by [Blackboard](https://www.blackboard.com/it-it) and have been carefully anonymized and securely stored to preserve privacy.

## 🎓 24-25 Students Performance Analysis

Based on the data from the 2024-2025 academic year, here's a comprehensive analysis of student performance:

### Overall Statistics

<table>
<caption>(\#tab:performance-analysis-24-25)Summary Statistics for 2024-2025 Academic Year</caption>
 <thead>
  <tr>
   <th style="text-align:right;"> Students </th>
   <th style="text-align:right;"> Mean Grade </th>
   <th style="text-align:right;"> Median Grade </th>
   <th style="text-align:right;"> Std Dev </th>
   <th style="text-align:right;"> Min Grade </th>
   <th style="text-align:right;"> Max Grade </th>
   <th style="text-align:right;"> Pass Rate (%) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 23.2 </td>
   <td style="text-align:right;"> 26.75 </td>
   <td style="text-align:right;"> 7.63 </td>
   <td style="text-align:right;"> 1.5 </td>
   <td style="text-align:right;"> 32.25 </td>
   <td style="text-align:right;"> 77.6 </td>
  </tr>
</tbody>
</table>



### Grade Distribution


\includegraphics[width=1\linewidth]{94-courseperformance_files/figure-latex/grade-distribution-1} 

### Intermediate Exam Performance

<table>
<caption>(\#tab:intermediate-analysis)Intermediate Exam Performance</caption>
 <thead>
  <tr>
   <th style="text-align:right;"> 1st Intermediate Mean </th>
   <th style="text-align:right;"> 2nd Intermediate Mean </th>
   <th style="text-align:right;"> 1st Intermediate Count </th>
   <th style="text-align:right;"> 2nd Intermediate Count </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 23.26 </td>
   <td style="text-align:right;"> 27.07 </td>
   <td style="text-align:right;"> 41 </td>
   <td style="text-align:right;"> 30 </td>
  </tr>
</tbody>
</table>



### Performance by Exam Type


\includegraphics[width=1\linewidth]{94-courseperformance_files/figure-latex/exam-type-analysis-1} 

### Key Insights

1. **Overall Performance**: The mean final grade for the 2024-2025 academic year was 23.2 out of 30.

2. **Pass Rate**: 77.6% of students achieved a passing grade (≥18).

3. **Grade Range**: Final grades ranged from 1.5 to 32.25.

4. **Intermediate Exams**: Students performed similarly on both intermediate exams, with slight variations.

5. **Distribution**: The grade distribution shows a normal distribution with most students scoring in the middle range.

## 🎓 20-21 Students 


\includegraphics[width=1\linewidth]{images/perf_20-21} 

----


\includegraphics[width=1\linewidth]{images/perf_mg_20-21} 

## 🎓 21-22 Students

... soon to be analysed ...

## 🎓 22-23 Students

... soon to be analysed ...

## 🎓 23-24 Students

... soon to be analysed ...
